[general]
import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
normal = { family = "Hasklug Nerd Font Mono", style = "Regular" }
size = 10

[window]
dimensions = { columns = 130, lines = 40 }
