[general]
import = [
  "~/.config/alacritty/themes/themes/breeze.toml"
]

[font]
normal = { family = "Hasklug Nerd Font Mono Light", style = "Light,Regular" }
size = 10

[window]
dimensions = { columns = 130, lines = 40 }
