# GNU-Screen compatible prefix
set -g prefix2 C-a
bind C-a send-prefix -2

# start windows numbering at 1
set -g base-index 1

# make pane numbering consistent with windows
setw -g pane-base-index 1

# rename window to reflect current program
setw -g automatic-rename on

# renumber windows when a window is closed
set -g renumber-windows on

# set terminal title
set -g set-titles on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Theme
set -g @plugin 'egel/tmux-gruvbox'

# Other plugins
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager
run '/usr/share/tmux-plugin-manager/tpm'
